version: '3.1'

volumes:
  pg_demo:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=docker-demo
      - POSTGRES_USER=docker-demo
      - POSTGRES_DB=docker-demo
    volumes:
      - pg_demo:/var/lib/postgresql/data
    ports:
      - "10001:5432"
  app:
#    image:  1cf1a55531dc
    build: ..
    depends_on:
      - pg_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_db:5432/docker-demo
      - SPRING_DATASOURCE_USERNAME=docker-demo
      - SPRING_DATASOURCE_PASSWORD=docker-demo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8082:8082"