version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    networks:
      monitoring:
        aliases:
          - prometheus

networks:
  monitoring: