version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    links:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus
  app:
    image: 'eclipse-temurin:17.0.5_8-jdk-alpine'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/retail_rrcb_db_dev?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
#      - SPRING_DATASOURCE_USERNAME=retail_rrcb_db_dev
#      - SPRING_DATASOURCE_PASSWORD=retail_rrcb_db_dev
#      - SPRING_FLYWAY_SCHEMAS=retail_rrcb_db_dev
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      monitoring:


  terminal:
    image: 'ubuntu:bionic'
    stdin_open: true
    tty: true        # docker run -t
    networks:
      monitoring:

networks:
  monitoring: