version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    links:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus
  app:
    image: 'eclipse-temurin:17.0.5_8-jdk-alpine'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    networks:
      monitoring:

  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./infra/data/grafana:/var/lib/grafana:rw
    user: "${GRAFANA_USER_ID}"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    ports:
      - "3000:3000"
    links:
      - prometheus
    networks:
      monitoring:


  terminal:
    image: 'ubuntu:bionic'
    stdin_open: true
    tty: true        # docker run -t
    networks:
      monitoring:

networks:
  monitoring: